Traceback (most recent call last):
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/rewrites/macros.py", line 107, in _expand_callable_macro
    result = macro.func(*args, **kws)
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/cuda/stubs.py", line 119, in grid_expand
    raise ValueError('argument can only be 1, 2, 3')
ValueError: argument can only be 1, 2, 3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./vec-test.py", line 6, in <module>
    @cuda.jit('float32(float32[:])', device=True)
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/cuda/decorators.py", line 104, in device_jit
    debug=debug)
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/cuda/compiler.py", line 149, in compile_device
    return DeviceFunction(pyfunc, return_type, args, inline=True, debug=False)
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/cuda/compiler.py", line 180, in __init__
    debug=self.debug, inline=self.inline)
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/cuda/compiler.py", line 51, in compile_cuda
    locals={})
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/compiler.py", line 941, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/compiler.py", line 372, in compile_extra
    return self._compile_bytecode()
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/compiler.py", line 872, in _compile_bytecode
    return self._compile_core()
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/compiler.py", line 859, in _compile_core
    res = pm.run(self.status)
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/compiler.py", line 253, in run
    raise patched_exception
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/compiler.py", line 244, in run
    stage()
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/compiler.py", line 521, in stage_generic_rewrites
    self, self.func_ir)
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/rewrites/registry.py", line 70, in apply
    pipeline.calltypes)
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/rewrites/macros.py", line 64, in match
    const, rhs.loc)
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/rewrites/macros.py", line 113, in _expand_callable_macro
    raise errors.MacroError(newmsg)
numba.errors.MacroError: Failed in nopython mode pipeline (step: nopython rewrites)
Macro expansion failed at ./vec-test.py (8):
argument can only be 1, 2, 3
srun: error: gpu-0-0: task 0: Exited with exit code 1
